using UnityEngine;

public enum IntersectionType
{
    GREATCIRCLE_GREATCIRCLE_A,
    GREATCIRCLE_GREATCIRCLE_B,
    GREATCIRCLE_GREATCIRCLESEGMENT,
    GREATCIRCLESEGMENT_GREATCIRCLESEGMENT,
    SMALLCIRCLE_SMALLCIRCLE_A,
    SMALLCIRCLE_SMALLCIRCLE_B,
    SMALLCIRCLE_GREATCIRCLE_A,
    SMALLCIRCLE_GREATCIRCLE_B,
    SMALLCIRCLE_GREATCIRCLESEGMENT_A,
    SMALLCIRCLE_GREATCIRCLESEGMENT_B,
}
